from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, IncludeLaunchDescription
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node, SetParameter
from ament_index_python.packages import get_package_share_directory
import os

# Default map output location (generated by run_astar_navigation.sh Step 0)
_DEFAULT_MAP_YAML = os.path.join(
    os.path.expanduser("~"), "ros2_maps", "large_messy_room_map.yaml"
)


def generate_launch_description():
    """
    Launch file for A* path planning demonstration with point cloud mapping
    - Gazebo simulation with TurtleBot rover
    - NO moving humans (disabled temporarily)
    - A* path planner for goal-based navigation
    - Point cloud mapper for real-time obstacle detection and mapping
    """
    world = LaunchConfiguration("world")
    default_goal_x = LaunchConfiguration("default_goal_x")
    default_goal_y = LaunchConfiguration("default_goal_y")
    map_yaml = LaunchConfiguration("map_yaml")

    # Get package share directory for world files
    pkg_share = get_package_share_directory("ros_humans_ros2")
    default_world = os.path.join(pkg_share, "worlds", "large_messy_room.world")

    gazebo_launch = os.path.join(
        get_package_share_directory("ros_gz_sim"),
        "launch",
        "gz_sim.launch.py",
    )

    return LaunchDescription([
        # Use simulation time for all nodes
        SetParameter(name='use_sim_time', value=True),
        
        DeclareLaunchArgument(
            "world",
            default_value=default_world,
            description="Gazebo world file",
        ),
        DeclareLaunchArgument(
            "default_goal_x",
            default_value="5.0",
            description="Default goal X coordinate",
        ),
        DeclareLaunchArgument(
            "default_goal_y",
            default_value="5.0",
            description="Default goal Y coordinate",
        ),
        DeclareLaunchArgument(
            "map_yaml",
            default_value=_DEFAULT_MAP_YAML,
            description="Path to the pre-generated world map YAML "
                        "(produced by world_to_map node from the .world file)",
        ),
        IncludeLaunchDescription(
            PythonLaunchDescriptionSource(gazebo_launch),
            launch_arguments={"gz_args": ["-r ", world]}.items(),
        ),
        # Clock bridge (Gazebo -> ROS2) - CRITICAL for time sync
        Node(
            package="ros_gz_bridge",
            executable="parameter_bridge",
            name="clock_bridge",
            output="screen",
            arguments=[
                "/clock@rosgraph_msgs/msg/Clock[gz.msgs.Clock"
            ],
        ),
        # NOTE: The Gazebo Pose_V→TFMessage bridge was REMOVED here.
        # It published ground-truth TFs for ALL entities (including
        # turtlebot3_rover → base_footprint, base_link, lidar_link, …)
        # which conflicted with our odom → base_footprint → base_link chain,
        # causing the LaserScan / pointcloud overlay to drift during turns.
        # TurtleBot rover cmd_vel bridge (ROS2 -> Gazebo)
        Node(
            package="ros_gz_bridge",
            executable="parameter_bridge",
            name="turtlebot_cmd_vel_bridge",
            output="screen",
            arguments=[
                "/cmd_vel@geometry_msgs/msg/Twist]gz.msgs.Twist",
                "/model/turtlebot3_rover/cmd_vel@geometry_msgs/msg/Twist]gz.msgs.Twist"
            ],
        ),
        # TurtleBot rover odometry bridge (Gazebo -> ROS2)
        Node(
            package="ros_gz_bridge",
            executable="parameter_bridge",
            name="turtlebot_odom_bridge",
            output="screen",
            arguments=[
                "/odom@nav_msgs/msg/Odometry[gz.msgs.Odometry"
            ],
        ),
        # TurtleBot LiDAR scan bridge (Gazebo -> ROS2)
        Node(
            package="ros_gz_bridge",
            executable="parameter_bridge",
            name="turtlebot_scan_bridge",
            output="screen",
            arguments=[
                "/scan@sensor_msgs/msg/LaserScan[gz.msgs.LaserScan"
            ],
        ),
        # Camera bridges (Gazebo -> ROS2)
        Node(
            package="ros_gz_bridge",
            executable="parameter_bridge",
            name="camera_front_bridge",
            output="screen",
            arguments=[
                "/camera/front/image@sensor_msgs/msg/Image[gz.msgs.Image"
            ],
        ),
        Node(
            package="ros_gz_bridge",
            executable="parameter_bridge",
            name="camera_right_bridge",
            output="screen",
            arguments=[
                "/camera/right/image@sensor_msgs/msg/Image[gz.msgs.Image"
            ],
        ),
        Node(
            package="ros_gz_bridge",
            executable="parameter_bridge",
            name="camera_back_bridge",
            output="screen",
            arguments=[
                "/camera/back/image@sensor_msgs/msg/Image[gz.msgs.Image"
            ],
        ),
        Node(
            package="ros_gz_bridge",
            executable="parameter_bridge",
            name="camera_left_bridge",
            output="screen",
            arguments=[
                "/camera/left/image@sensor_msgs/msg/Image[gz.msgs.Image"
            ],
        ),
        # ── STATIC WORLD MAP ─────────────────────────────────────────────────
        # Loads the .pgm/.yaml generated by world_to_map (Step 0 of the run
        # script) and publishes it to /map with TRANSIENT_LOCAL QoS so any
        # late-joining subscriber (including astar_path_planner) gets the map.
        Node(
            package="ros_humans_ros2",
            executable="map_publisher",
            name="map_publisher",
            output="screen",
            parameters=[{
                "yaml_file": map_yaml,
                "publish_rate": 0.5,   # 0.5 Hz is plenty – map is static
                "frame_id": "map",
                "use_sim_time": True,
            }],
        ),
        # Localization node: fuses odom + spawn offset, publishes /robot_pose
        # Required for human_detector_red to convert camera detections to world frame
        Node(
            package="ros_humans_ros2",
            executable="localization_node",
            name="localization_node",
            output="screen",
            parameters=[{
                "spawn_x": 0.0,
                "spawn_y": -8.0,
                "spawn_yaw": 1.5708,
                "use_sim_time": True,
            }],
        ),
        # A* Path Planner (replaces rover_explorer for goal-based navigation)
        Node(
            package="ros_humans_ros2",
            executable="astar_path_planner",
            name="astar_path_planner",
            output="screen",
            parameters=[{
                "linear_speed": 0.3,
                "angular_speed": 0.5,
                "goal_tolerance": 0.3,
                "grid_resolution": 0.2,
                "grid_size": 140,        # overridden once static /map arrives
                # Room bounds match the generated 28 m × 28 m map
                # (origin -14,-14 → +14,+14 with 1 m safety margin)
                "room_min_x": -13.0,
                "room_max_x":  13.0,
                "room_min_y": -13.0,
                "room_max_y":  13.0,
                "obstacle_inflation": 0.60,
                "auto_start": True,
                "default_goal_x": default_goal_x,
                "default_goal_y": default_goal_y,
                # Rover spawns at (0, -8, yaw=90°) in large_messy_room.world.
                # These offsets rotate+translate odom (0,0,yaw=0) → world (0,-8,yaw=90°).
                "spawn_x": 0.0,
                "spawn_y": -8.0,
                "spawn_yaw": 1.5708,
                # Human-aware planning parameters
                "human_inflation_radius": 0.8,
                "human_predict_horizon": 3.0,
                "human_costmap_weight": 60,
                "human_replan_dist": 4.0,
                "use_sim_time": True
            }],
        ),
        # Point cloud mapper (for real-time mapping and visualization)
        Node(
            package="ros_humans_ros2",
            executable="pointcloud_mapper",
            name="pointcloud_mapper",
            output="screen",
            parameters=[{
                "map_frame": "map",
                "robot_frame": "base_footprint",
                "max_points": 30000,
                "map_resolution": 0.1,
                "map_size": 28.0,
                # Rover spawn pose so map→odom TF is correct
                "spawn_x": 0.0,
                "spawn_y": -8.0,
                "spawn_yaw": 1.5708,
                "max_scan_range": 6.0,           # shorter range = less noise
                "point_lifetime": 5.0,           # 5s window (was 15s)
                "min_move_dist": 0.05,           # skip accumulation when stationary
                "publish_accumulated_cloud": True,
                "use_sim_time": True
            }],
        ),
        # 360 camera view combiner
        Node(
            package="ros_humans_ros2",
            executable="camera_view_360",
            name="camera_view_360",
            output="screen",
            parameters=[{"use_sim_time": True}],
        ),
        
        # NOTE: Moving humans are ENABLED with CV-based detection
        # Human mover: animates the 5 moving humans along waypoints
        Node(
            package="ros_gz_bridge",
            executable="parameter_bridge",
            name="set_pose_bridge",
            output="screen",
            arguments=[
                "/world/large_messy_room/set_pose@ros_gz_interfaces/srv/SetEntityPose"
            ],
        ),
        Node(
            package="ros_humans_ros2",
            executable="move_humans",
            name="move_humans",
            output="screen",
            parameters=[{"rate": 10.0, "world": "large_messy_room", "use_sim_time": True}],
        ),
        # NOTE: publish_human_pose was REMOVED — it depended on the
        # Pose_V TF bridge (removed above) and nothing subscribes to
        # /human_pose.  Human positions are detected by human_detector_red.
        # RED-colour human detector — detects full-red humans from cameras
        # and publishes their positions + velocities for A* replanning
        Node(
            package="ros_humans_ros2",
            executable="human_detector_red",
            name="human_detector_red",
            output="screen",
            parameters=[{
                "detection_rate": 5.0,
                "min_contour_area": 100,
                "max_detect_range": 12.0,
                "track_timeout": 1.5,
                "publish_timeout": 0.6,
                # Red HSV thresholds (red wraps around H=0/180)
                "red_h_low1": 0,
                "red_h_high1": 15,
                "red_h_low2": 165,
                "red_h_high2": 180,
                "red_s_min": 50,
                "red_v_min": 50,
                "cam_focal_px": 320.0,
                "reference_size": 0.5,         # human body diameter ~0.5m
                "reference_height": 1.7,       # human body height ~1.7m
                "cam_hfov_deg": 90.0,
                "use_lidar_fusion": True,
                "lidar_bearing_tolerance": 0.15,
                "show_debug_window": True,
                "use_sim_time": True,
            }],
        ),
    ])
